apiVersion: v1
kind: Pod
metadata:
  name: apline-curl
  namespace: otel-col
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - fastapi-app
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: alpine
    image: alpine
    command: ["sh", "-c", "sleep 3600"]
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "apk add --no-cache curl"]
    volumeMounts:
    - name: script-volume
      mountPath: /scripts
  volumes:
  - name: script-volume
    configMap:
      name: traffic-simulation-script